version: '3.7'

services:
  catalog-service:
    image: cksghks89/catalog-service:1.0
    container_name: catalog-service
    environment:
      - "spring.cloud.config.uri=http://config-service:8888"
      - "spring.rabbitmq.host=rabbitmq"
      - "eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/"
      - "logging.file=/api-logs/catalog-ws.log"
      - "my.kafka.ip=172.19.0.101:29092"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true
