version: '3.7'

services:
  order-service:
    image: cksghks89/order-service:1.0
    container_name: order-service
    environment:
      - "spring.cloud.config.uri=http://config-service:8888"
      - "spring.rabbitmq.host=rabbitmq"
      - "spring.datasource.url=jdbc:mysql://mysql:3306/mydb"
      - "management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans"
      - "eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/"
      - "my.kafka.ip=172.19.0.101:29092"
      - "logging.file=/api-logs/users-ws.log"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true