version: "3.7"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - ecommerce-network

volumes:
  mysql-volume:
    external: true

networks:
  ecommerce-network:
    external: true
