version: "3.7"

services:
  service-discovery:
    image: cksghks89/service-discovery:1.0
    container_name: service-discovery
    ports:
      - "8761:8761"
    environment:
      - "spring.cloud.config.uri=http://config-service:8888"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true