server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cksghks89/MSA-Market
          default-label: develop
          search-paths: config-files
#          username: [ username ]    # private Repository 의 경우 username, password 기입
#          passphrase: [ password ]